"""Create the languages table

Revision ID: 103fdf8903e8
Revises: a0fc601d5534
Create Date: 2024-10-27 09:22:40.287302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103fdf8903e8'
down_revision = 'a0fc601d5534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('experience', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Languages')
    # ### end Alembic commands ###
