"""create all tables

Revision ID: dc737e476d37
Revises: 
Create Date: 2024-10-27 19:43:51.538401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc737e476d37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Institutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('experience', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('profile_bio', sa.String(), nullable=False),
    sa.Column('employed', sa.Boolean(), nullable=False),
    sa.Column('open_to_work', sa.Boolean(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('home_country', sa.String(), nullable=False),
    sa.Column('home_town', sa.String(), nullable=False),
    sa.Column('current_country', sa.String(), nullable=False),
    sa.Column('current_town', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('git_hub_link', sa.String(), server_default='', nullable=False),
    sa.Column('linkdn_link', sa.String(), server_default='', nullable=False),
    sa.Column('insta_link', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('git_hub_link', sa.String(), nullable=True),
    sa.Column('blog_link', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['Institutes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projectPoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projectPoints')
    op.drop_table('Projects')
    op.drop_table('profile')
    op.drop_table('Languages')
    op.drop_table('Institutes')
    # ### end Alembic commands ###
