"""create profile table

Revision ID: f4574a3a0891
Revises: 
Create Date: 2024-10-26 17:42:53.368909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4574a3a0891'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('profile_bio', sa.String(), nullable=False),
    sa.Column('employed', sa.Boolean(), nullable=False),
    sa.Column('open_to_work', sa.Boolean(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('home_country', sa.String(), nullable=False),
    sa.Column('home_town', sa.String(), nullable=False),
    sa.Column('current_country', sa.String(), nullable=False),
    sa.Column('current_town', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
